# docker-compose.yml
version: "3.8"

services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    env_file:
      - .env
# Uncomment the following section to include a PostgreSQL database setup:
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB=example
#       POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: ["CMD", "pg_isready"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
